### ISSUE TITLE
在使用了橡皮檫之后 在使用其他与颜色有关工具之前 应该切换当前的工具

### ISSUE THREAD

**Issue by feixierman** [OXOYO/XBoard#3]

**Comment by OXOYO** [comment]
可能应该在擦除时禁用颜色相关工具，是这个意思吗

**Comment by feixierman** [comment]
还有一个 改变了背景色之后 橡皮檫还是擦出白色的底  但这个时候把窗口大小改变一下 就会变成正常的橡皮檫

**Comment by feixierman** [comment]
> 可能应该在擦除时禁用颜色相关工具，是这个意思吗

我现在只用到了铅笔颜色和背景色这2个 所有我改变着两个颜色之前我调用了选择铅笔的方法 这样就可以再次改变背景色  不然在改变一次背景色之后使用了橡皮檫之后就不能再次改变背景色了

**Comment by feixierman** [comment]
https://github.com/szimek/signature_pad/issues/421
