### ISSUE TITLE
一个有趣的BUG

### ISSUE THREAD

**Issue by weathon** [OXOYO/XBoard#6]
在触屏电脑上用两个手指同时画画会出现下图额度神奇现象
![Screenshot 2020-01-15 at 2 41 55 PM](https://user-images.githubusercontent.com/41298844/72469528-3239c600-37a5-11ea-9e2c-9b4faa548ab4.png)

**Comment by weathon** [comment]
![XBoard_20200115153252](https://user-images.githubusercontent.com/41298844/72473497-6c5a9600-37ac-11ea-9706-9c6dfe9fa1dc.png)
geng duo shou zhi更多手指同时画
不修复也可以，挺有趣的。或者弄一个开关可以

**Comment by OXOYO** [comment]
@weathon 感谢反馈，暂时还没考虑到这种情况以及双指绘画的需求，后期可以在这么方面扩展。

**Comment by weathon** [comment]
> @weathon 感谢反馈，暂时还没考虑到这种情况以及双指绘画的需求，后期可以在这么方面扩展。

那就不用修复了，这么画着挺有艺术感的

**Comment by Meihina** [comment]
> > @weathon 感谢反馈，暂时还没考虑到这种情况以及双指绘画的需求，后期可以在这么方面扩展。
> 
> 那就不用修复了，这么画着挺有艺术感的

意外的笔刷功能w
